public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");

        int baby = 1;
        System.out.println("Значение переменной  baby c типом int равно " + baby);
        byte dog = 2;
        System.out.println("Значение переменной  dog c типом byte равно " + dog);
        short cat = 3;
        System.out.println("Значение переменной  cat c типом shot равно " + cat);
        long dad = 4L;
        System.out.println("Значение переменной  dad c типом long равно " + dad);
        float mam = 5f;
        System.out.println("Значение переменной  mam c типом float равно " + mam);
        double sister = 1f;
        System.out.println("Значение переменной  sister c типом double равно " + sister);
        System.out.println("Задача 2");
        double one = 27.12;
        long two = 987678965549L;
        float three = 2f;
        short four = 786;
        boolean five = false;
        int six = 569;
        short seven = -159;
        int eight = 27897;
        byte nine = 67;
        System.out.println("Сделана");
        System.out.println("Задача 3");
        byte pupilsLydmilaPavlovna = 23;
        byte pupilsAnnaSergeevna = 27;
        byte pupilsEkaterinaAndreevna = 30;
        int shortPupils = pupilsEkaterinaAndreevna + pupilsAnnaSergeevna + pupilsLydmilaPavlovna;
        double totalPaper = 430;
        double paperOnPupils = totalPaper / shortPupils ;
        System.out.println("На каждого ученика рассчитано " + paperOnPupils + " листов бумаги");
        System.out.println("Задача 4");
        double bottles = 16;
        int time = 2;
        double bottlesOneTime = bottles / time;
        System.out.println("Машина производит бутылок в минуту " + bottlesOneTime);
        double bottlesOn20Min = bottlesOneTime * 20;
        System.out.println("За 20 минут машина произвела бутылок " + bottlesOn20Min + " штук");
        double bottlesOnOneDay = bottlesOneTime * 24 * 60;
        System.out.println("За 1 сутки машина произвела бутылок " + bottlesOnOneDay + " штук");
        double bottlesOnThreeDay = bottlesOneTime * 24 * 60 * 3;
        System.out.println("За 3 суток машина произвела бутылок " + bottlesOnThreeDay + " штук");
        double bottlesOnOneMon = bottlesOneTime * 24 * 60 * 30;
        System.out.println("За 3 суток машина произвела бутылок " + bottlesOnOneMon + " штук");
        System.out.println("Задача 5");
        byte red = 4;
        byte white = 2;
        int sum = red + white ;
        double total = 120;
        double clas = 120 / sum;
        System.out.println("В школе, где " + clas + " классов, нужно " + white * clas + " банок белой краски и " + red * clas +
                " банок коричневой краски");
        System.out.println("Задача 6");
        int banan = 80;
        int milk = 105;
        int ice = 100;
        int eygs = 70;
        double breakfastGramm = banan * 5 + milk * 2 + ice * 2 + eygs * 4;
        double breakfastKg = breakfastGramm / 1000;
        System.out.println("Завтрак в граммах " + breakfastGramm + "гр. Завтрак в килограммах " + breakfastKg + "кг.");
        System.out.println("Задача 7");
        double weight = 7000;
        int weightOne = 250;
        int weightTwo = 500;
        double dayOne = weight / weightOne;
        double dayTwo = weight / weightTwo;
        double dayAverage = (dayOne + dayTwo) / 2;
        System.out.println("Дней при 250 грамм в день: " + dayOne);
        System.out.println("Дней при 500 грамм в день: " + dayTwo);
        System.out.println("Дней в среднем: " + dayAverage);
        System.out.println("Задача 8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        double newMasha = masha + masha * 0.1;
        double newDenis = denis + denis * 0.1;
        double newKristina = kristina + kristina * 0.1;
        double yearNewMasha = (newMasha - masha) * 12 ;
        double yearNewDenis = (newDenis - denis) * 12;
        double yearNewKristina = (newKristina - kristina) * 12;
        System.out.println("Маша теперь получает " + newMasha + " рублей. Годовой доход вырос на " + yearNewMasha + " рублей");
        System.out.println("Денис теперь получает " + newDenis + " рублей. Годовой доход вырос на " + yearNewDenis + " рублей");
        System.out.println("Кристина теперь получает " + newKristina + " рублей. Годовой доход вырос на " + yearNewKristina + " рублей");
            }
}